return {
  layout = "ivy",
  win = {
    -- input window
    input = {
      keys = {
        -- to close the picker on ESC instead of going to normal mode,
        -- add the following keymap to your config
        -- ["<Esc>"] = { "close", mode = { "n", "i" } },
        ["/"] = "toggle_focus",
        ["<C-Down>"] = { "history_forward", mode = { "i", "n" } },
        ["<C-Up>"] = { "history_back", mode = { "i", "n" } },
        ["<C-c>"] = { "close", mode = "i" },
        ["<C-w>"] = { "<c-s-w>", mode = { "i" }, expr = true, desc = "delete word" },
        ["<CR>"] = { "confirm", mode = { "n", "i" } },
        ["<Down>"] = { "list_down", mode = { "i", "n" } },
        ["<Esc>"] = "close",
        ["<S-CR>"] = { { "pick_win", "jump" }, mode = { "n", "i" } },
        ["<S-Tab>"] = { "select_and_prev", mode = { "i", "n" } },
        ["<Tab>"] = { "select_and_next", mode = { "i", "n" } },
        ["<Up>"] = { "list_up", mode = { "i", "n" } },
        ["<A-d>"] = { "inspect", mode = { "n", "i" } },
        ["<A-f>"] = { "toggle_follow", mode = { "i", "n" } },
        ["<A-h>"] = { "toggle_hidden", mode = { "i", "n" } },
        ["<A-i>"] = { "toggle_ignored", mode = { "i", "n" } },
        ["<A-m>"] = { "toggle_maximize", mode = { "i", "n" } },
        ["<C-space>"] = { "toggle_preview", mode = { "i", "n" } },
        ["<A-w>"] = { "cycle_win", mode = { "i", "n" } },
        ["<C-a>"] = { "select_all", mode = { "n", "i" } },
        ["<C-b>"] = { "preview_scroll_up", mode = { "i", "n" } },
        ["<C-d>"] = { "list_scroll_down", mode = { "i", "n" } },
        ["<C-f>"] = { "preview_scroll_down", mode = { "i", "n" } },
        ["<C-g>"] = { "toggle_live", mode = { "i", "n" } },
        ["<C-j>"] = { "list_down", mode = { "i", "n" } },
        ["<C-k>"] = { "list_up", mode = { "i", "n" } },
        ["<C-n>"] = { "list_down", mode = { "i", "n" } },
        ["<C-p>"] = { "list_up", mode = { "i", "n" } },
        ["<C-q>"] = { "qflist", mode = { "i", "n" } },
        ["<C-s>"] = { "edit_split", mode = { "i", "n" } },
        ["<C-u>"] = { "list_scroll_up", mode = { "i", "n" } },
        ["<C-v>"] = { "edit_vsplit", mode = { "i", "n" } },
        ["<C-z>h"] = { "layout_left", mode = { "i", "n" } },
        ["<C-z><C-h>"] = { "layout_left", mode = { "i", "n" } },
        ["<C-z>j"] = { "layout_bottom", mode = { "i", "n" } },
        ["<C-z><C-j>"] = { "layout_bottom", mode = { "i", "n" } },
        ["<C-z>k"] = { "layout_top", mode = { "i", "n" } },
        ["<C-z><C-k>"] = { "layout_top", mode = { "i", "n" } },
        ["<C-z>l"] = { "layout_right", mode = { "i", "n" } },
        ["<C-z><C-l>"] = { "layout_right", mode = { "i", "n" } },
        ["?"] = "toggle_help_input",
        ["G"] = "list_bottom",
        ["gg"] = "list_top",
        ["j"] = "list_down",
        ["k"] = "list_up",
        ["q"] = "close",
      },
    },
    -- result list window
    list = {
      keys = {
        ["/"] = "toggle_focus",
        ["<2-LeftMouse>"] = "confirm",
        ["<CR>"] = "confirm",
        ["<Down>"] = "list_down",
        ["<Esc>"] = "close",
        ["<S-CR>"] = { { "pick_win", "jump" } },
        ["<S-Tab>"] = { "select_and_prev", mode = { "n", "x" } },
        ["<Tab>"] = { "select_and_next", mode = { "n", "x" } },
        ["<Up>"] = "list_up",
        ["<A-d>"] = "inspect",
        ["<A-f>"] = "toggle_follow",
        ["<A-h>"] = "toggle_hidden",
        ["<A-i>"] = "toggle_ignored",
        ["<A-m>"] = "toggle_maximize",
        -- ["<A-p>"] = "toggle_preview",
        ["<A-w>"] = "cycle_win",
        ["<C-a>"] = "select_all",
        ["<C-b>"] = "preview_scroll_up",
        ["<C-d>"] = "list_scroll_down",
        ["<C-f>"] = "preview_scroll_down",
        ["<C-j>"] = "list_down",
        ["<C-k>"] = "list_up",
        ["<C-n>"] = "list_down",
        ["<C-p>"] = "list_up",
        ["<C-s>"] = "edit_split",
        ["<C-u>"] = "list_scroll_up",
        ["<C-v>"] = "edit_vsplit",
        ["<C-z>h"] = { "layout_left", mode = { "i", "n" } },
        ["<C-z><C-h>"] = { "layout_left", mode = { "i", "n" } },
        ["<C-z>j"] = { "layout_bottom", mode = { "i", "n" } },
        ["<C-z><C-j>"] = { "layout_bottom", mode = { "i", "n" } },
        ["<C-z>k"] = { "layout_top", mode = { "i", "n" } },
        ["<C-z><C-k>"] = { "layout_top", mode = { "i", "n" } },
        ["<C-z>l"] = { "layout_right", mode = { "i", "n" } },
        ["<C-z><C-l>"] = { "layout_right", mode = { "i", "n" } },
        ["?"] = "toggle_help_list",
        ["G"] = "list_bottom",
        ["gg"] = "list_top",
        ["i"] = "focus_input",
        ["j"] = "list_down",
        ["k"] = "list_up",
        ["q"] = "close",
        ["zb"] = "list_scroll_bottom",
        ["zt"] = "list_scroll_top",
        ["zz"] = "list_scroll_center",
      },
    },
    -- preview window
    preview = {
      keys = {
        ["<Esc>"] = "close",
        ["q"] = "close",
        ["i"] = "focus_input",
        ["<ScrollWheelDown>"] = "list_scroll_wheel_down",
        ["<ScrollWheelUp>"] = "list_scroll_wheel_up",
        ["<A-w>"] = "cycle_win",
      },
    },
  },
}
